### ISSUE TITLE
Support for multiple content dimensions

### ISSUE THREAD

**Issue by beromir** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#23]
Your package is really great and we would love to use it on our website, but there is a problem with our multilingual setup.

We have two languages registered as content dimensions in the settings.yaml:

```yml
Neos:
  ContentRepository:
      contentDimensions:
        language:
          label: 'Language'
          icon: icon-globe-europe
          default: de
          defaultPreset: de
          resolution:
            mode: 'topLevelDomain'
          presets:
            eu_EN:
              label: 'EU'
              values:
                - eu_EN
                - en_UK
              uriSegment: eu
            de:
              label: 'DE'
              values:
                - de
              uriSegment: de

```

We thought we could create the cookie consent page in either dimension/language. And it will recognize the dimension the user is in and it will display the cookie consent with the settings we have set for the dimension.

For example, we have different cookie consent texts on the German and English sites. But unfortunately, the cookie consent shows the text of the German dimension in all dimensions.

Is this already possible or is there a way to achieve this?
